RDFLib/prez

- prez/cql_search.py
> Improve search performance by changing string matching to token match

- .gitignore
- Dockerfile
- prez/models/vocprez/vocprez_scheme.py
- prez/services/sparql_utils.py
Reduces the Docker image from ~450 -> 310 MB by doing the Python stuff separately to the file transfer and also by using autoremove.
> Smaller docker image

- prez/models/catprez/catprez_resource.py
- prez/models/vocprez/vocprez_concept.py
- prez/services/spaceprez_service.py
tiny PR for missing NS in queries
assume we haven't seen the issue before as Fuseki often just knows about SKOS as a namespace but not this time!
> add in SKOS namespaces

- .dockerignore
- Dockerfile
Based on a Dockerfile I've used elsewhere. Uses a multi-stage build and reduces size to ~200 MB
> Slimmer dockerfile

- prez/models/spaceprez/spaceprez_dataset.py
- prez/utils.py
Bugfix for including templates in docker containers, and adding dcterms:spatial to the recognised prefixes so that maps for dcat:Datasets display
> templates Dataset map display bugfixes

- README-Dev.md
As requested in the (separate) PR for CURIE changes, updated doco on how they are used.
Let me know if you there any major gaps.
Could definitely write more but I think most of it would be low level implementation specific detail.
> Update dev doco

- prez/models/vocprez_item.py
- tests/data/vocprez/expected_responses/collection_listing_item.ttl
- tests/data/vocprez/expected_responses/vocab_anot.ttl
Closes https://github.com/RDFLib/prez-ui/issues/31
> Update VocPrez prez:links structure for concept schemes and collections

- .github/workflows/on_push_to_main.yaml
Same issue as described in the Prez UI PR here https://github.com/RDFLib/prez-ui/pull/55.
> Fix dev image tag version

- prez/config.py
- prez/routers/sparql.py
As mentioned in #113. Also includes a minor typo fix.
> Minor fix for SPARQL results duplication for flavours pointing to same endpoint

- prez/reference_data/profiles/catprez_default_profiles.ttl
- prez/sparql/objects_listings.py
- tests/catprez/test_endpoints_catprez.py
- tests/data/catprez/expected_responses/catalog_anot.ttl
- tests/data/catprez/expected_responses/resource_anot.ttl
CatPrez profile changes for https://github.com/RDFLib/prez-ui/issues/57.
Fixes `sh:sequencePath` in "object listing" query and aligns it with listing query changes introduced in https://github.com/RDFLib/prez/pull/107.
> Catalog object resource listing table metadata

- prez/queries/vocprez.py
It looks like the SPARQL queries that are currently used for VocPrez to retrieve the top concepts and narrower concepts do not work in GraphDB.
I've re-written the queries to ensure that they now work with both Fuseki and GraphDB.
This bug was found by Engineers Australia where they were setting up an instance of VocPrez. Inform them once this fix has made it into a release.
> Fix VocPrez queries not working on GraphDB

- Dockerfile
The reason for moving from a Debian to Alpine is due to the critical vulnerabilities that exist in the base Debian image. Most organisational cloud infrastructures block the deployment of such images containing critical vulnerabilities.
The critical vulnerabilities cannot be fixed immediately until the fixes are published to Debian's package repository.
At this moment in time, the Debian-based Prez image contains the following vulnerabilities:
> Total: 186 (UNKNOWN: 2, LOW: 101, MEDIUM: 44, HIGH: 37, CRITICAL: 2)
There are a lot less vulnerabilities in the Alpine image.
```
prez (alpine 3.19.1)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
2024-02-28T17:00:48.506+1000    INFO    Table result includes only package filenames. Use '--format json' option to get the full path …
```
> Add alpine-based Dockerfile

- .github/workflows/on_release.yaml
Updates the various gh actions steps to the latest version.
> Update gh action versions for on_release workflow

- pyproject.toml
Dependency introduced by PR #223
> update poetry-core version to 1.9.0

- README-Dev.md
- prez/reference_data/prefixes/standard.ttl
- prez/reference_data/prez_ns.py
- prez/reference_data/profiles/catprez_default_profiles.ttl
- prez/reference_data/profiles/prez_default_profiles.ttl
- prez/reference_data/profiles/spaceprez_default_profiles.ttl
- prez/reference_data/profiles/vocprez_default_profiles.ttl
- prez/renderers/renderer.py
- prez/services/listings.py
- prez/services/objects.py
- prez/sparql/objects_listings.py
- tests/data/profiles/remote_profile.ttl
Replace typo across all instances in the codebase
> Fix typo in connegp ontology prefix

- prez/reference_data/context_ontologies/prez-ontology.nq
- tests/data/catprez/expected_responses/catalog_anot.ttl
- tests/data/catprez/expected_responses/catalog_listing_anot.ttl
- tests/data/catprez/expected_responses/resource_anot.ttl
- tests/data/catprez/expected_responses/resource_listing_anot.ttl
- tests/data/object/expected_responses/fc.ttl
- tests/data/object/expected_responses/feature.ttl
- tests/data/search/expected_responses/filter_to_focus_search.ttl
- tests/data/search/expected_responses/focus_to_filter_search.ttl
- tests/data/spaceprez/expected_responses/dataset_anot.ttl
- tests/data/spaceprez/expected_responses/dataset_listing_anot.ttl
- tests/data/spaceprez/expected_responses/feature_anot.ttl
- tests/data/spaceprez/expected_responses/feature_collection_anot.ttl
- tests/data/spaceprez/expected_responses/feature_collection_listing_anot.ttl
- tests/data/spaceprez/expected_responses/feature_listing_anot.ttl
- tests/data/vocprez/expected_responses/collection_listing_anot.ttl
- tests/data/vocprez/expected_responses/collection_listing_item.ttl
- tests/data/vocprez/expected_responses/concept-open-cut-coal-mining.ttl
- tests/data/vocprez/expected_responses/vocab_listing_anot.ttl
and update test data to reflect the new labels.
> add prez ontology annotations.

- poetry.lock
- prez/config.py
- prez/reference_data/profiles/ogc_records_profile.ttl
- prez/reference_data/profiles/prez_default_profiles.ttl
- prez/services/connegp_service.py
- pyproject.toml
- tests/test_endpoints_profiles.py
Add connegp debug print output; adds tabulate development dependency. Reduce pagination count limit to 100.
> Add profiles profile.

- poetry.lock
- pyproject.toml
- tests/test_ogc.py
Draft PR, todo:
Is this expected:
> Integrate OGC Features tests

- prez/models/query_params.py
> fix: openapi schema should have example not examples under schema

- test_data/vocprez.ttl
> Add vocprez test data, replaces PR #220

- prez/routers/management.py
Lists all prefixes used by Prez. Allows RDF Mediatypes + JSON
> Add /prefixes endpoint

- prez/services/link_generation.py
- test_data/issue_286.ttl
- tests/test_issue_286.py
> Do not attempt to create link for certain classes.

- prez/services/curie_functions.py
- tests/conftest.py
- tests/test_curie_endpoint.py
keep vowels but remove all punctuation characters as per #287
> keep vowels in generated prefixes #287

- .github/workflows/manual_tests.yaml
- .github/workflows/on_pr_to_main.yaml
- .github/workflows/pr.yaml
- .releaserc.yaml
- commitlint.config.js
First testing not using CC PR title, then updating PR title CC compliant title should re-run linting.
> feat: update semantic release process

- prez/services/app_service.py
only retrieve NodeShapes specific to the remote endpoints being retrieved. Because all remote NodeShapes were being retrieved, where their URIs clashed with default NodeShape URIs, this produced undesired "union" shapes.
> fix: retrieve only relevant remote nodeshapes

- poetry.lock
- prez/renderers/renderer.py
- prez/services/listings.py
- pyproject.toml
change reviewed / tested w/ Ashley
> fix: update geojson conversion

- prez/services/query_generation/shacl.py
- tests/test_property_selection_shacl.py
TODO add a test
addresses #363
> fix: create different predicates for "all predicate values"

- .github/workflows/pr.yaml
- poetry.lock
- pyproject.toml
- adds docker build to PR tests to prevent merging PRs to main and finding the Dockerfile does not build
- updates deps which were the cause of the Dockerfile not building
> fix: update deps and add docker build to pr tests

- prez/services/query_generation/grammar_helpers.py
- tests/test_cql.py
- **wip**
- **finalise logic**
- **add tests**
- **black**
> fix: allow specification of datatypes in cql filter values
