RDFLib/prez

.github/workflows/on_push_to_feature.yaml, dev/dev-setup.py, prez/services/generate_profiles.py, tests/data/profiles/remote_profile.ttl, tests/local_sparql_store/store.py, tests/profiles/conftest.py, tests/profiles/test_endpoints_profiles.py
The `profiles_graph_cache` is using the `__add__` method which returns the combined statements in a new `Graph` instead of adding the new statements into `profiles_graph_cache`. This is why the remote profiles are never loaded.
Since `profiles_graph_cache` is a global variable imported elsewhere, we are not able to update its value. This is why something like the below won't work.
```python
profiles_graph_cache += r[1]
```
Instead, we add the triples from `r[1]` directly into `profiles_graph_cache`.
=> Fix loading remote profiles

prez/renderers/renderer.py, tests/data/vocprez/expected_responses/collection_listing_item.ttl, tests/vocprez/test_endpoints_vocprez.py
The endpoint at `/v/collection/<path-id>` throws a KeyError when accessing the dict that contains the inbound and outbound child links. This change fixes it by updating it to the new key values.
=> Fix rendering of VocPub SKOS Collections at /v/collection/<id>

.github/workflows/on_push_to_main.yaml, .github/workflows/on_release.yaml, README.md
This fixes https://github.com/RDFLib/prez/issues/100 by removing the use of the deprecated `::set-output` GH Actions syntax.
This PR also updates how container image tags are generated.
This change will continue to add the latest `major`, `major.minor` and `major.minor.patch` tags to the container image on releases.
It will no longer add the `stable` tag and instead, it will add the `latest` tag. The `latest` tag points to the latest stable release, and not the latest rolling dev builds.
For example, for a release with a git tag of `3.2.4`, the following tags will be on the container image:
- `3`
- `3.2`
- `3.2.4`
- `latest`
Dev builds will no longer add the `latest` tag and will only contain tags constructed from the commits made on `main` branch. The dev builds will be in the form of …
=> Remove deprecated GH Actions set-output usage. Update container image release tags

prez/app.py, prez/routers/update.py, prez/sparql/methods.py
This is a minimal implementation of prez exposing a SPARQL update endpoint.
It takes basic auth credentials supplied to one of the /c/update, /v/update, /s/update endpoints, along with a SPARQL update and passes these through to the corresponding backend SPARQL endpoints.
These changes have been minimally tested locally and against the current IDN Fuseki instance.
=> minimal implmementation of update endpoint

prez/sparql/methods.py
Resolves #76. Not clear on how/why the cache appends the results between requests, and apparently only on certain endpoints. Removed until the behaviour is better understood, or an alternate caching solution is introduced.
Does not resolve #16 if multiple Prez flavours are set to the same SPARQL endpoint. 
For #16 presumably Prez should deduplicate where the queries are sent - I don't want to make further changes until all of the expected behaviour is specified, or a decision is made to remove the use of multiple SPARQL endpoints.
Draft PR until above is resolved.
=> Remove caching on SPARQL query endpoint

prez/sparql/objects_listings.py, tests/sparql/test_object_listings.py
This fixes https://github.com/RDFLib/prez/issues/106.
Previous query with all the sequence predicates in a single OPTIONAL clause.
```sparql
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prez: <https://prez.dev/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT {
?top_level_item a <http://www.w3.org/2004/02/skos/core#ConceptScheme> .
?top_level_item <http://www.w3.org/ns/prov#qualifiedDerivation> ?seq_o1_0 .
?seq_o1_0 <http://www.w3.org/ns/prov#hadRole> ?seq_o2_0 .       
?top_level_item <http://www.w3.org/ns/prov#qualifiedDerivation> ?seq_o1_1 .
?seq_o1_1 <http://www.w3.org/ns/prov#entity> ?seq_o2_1 . …
```
=> Separate multiple sequence predicates into its own SPARQL OPTIONAL clause for the listing construct query

.github/workflows/on_release.yaml
Removes usage of deprecated set-output.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for more info.
=> Bump docker/metadata-action to v4 for on_release.yaml workflow

.github/workflows/on_push_to_main.yaml, .github/workflows/on_release.yaml, Dockerfile, prez/config.py, pyproject.toml
This PR adds the following to Prez:
- rolling dev version for changes to main
- release version
Our current official way of distributing Prez is via container images published here in this repo's GitHub Packages. Anyone who runs a container from there will be able to get the version by going to the route `/` and getting a response like the one below.
```
curl -X 'GET' 'http://localhost:8000'
```
```turtle
@prefix prez: <https://prez.dev/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
<http://localhost:8000> prez:currentTBOXCacheSize 0 ;
prez:enabledPrezFlavour [ a prez:ProfilesPrez ;
prez:link "/p" ],
[ a prez:CatPrez ;
prez:availableSearchMethod prez:exactMatch,
prez:jenaFTName ;
prez:link "/c" ],
[ a prez:SpacePrez ;
prez:availableSearchMethod prez:exactMatch,
prez:jenaFTName ; …
```
=> Add versioning on push to main and release

.github/workflows/on_release.yaml
I previously did not realise `docker/metadata-action` provides the full container name plus tag.
This fixes that and correctly sets the Docker build argument `PREZ_VERSION` with the semver version.
=> Fix release version formatting

prez/queries/vocprez.py, tests/local_sparql_store/store.py, tests/vocprez/test_endpoints_vocprez.py
The current set of vocprez queries to provide progressive loading of very large vocabs only supports `skos:hasTopConcept` and `skos:broader` relationships. This PR adds support for the same relationships and its inverse relationships, `skos:topConceptOf` and `skos:narrower`.
Fixes https://github.com/RDFLib/prez/issues/162.
=> Fix vocprez queries to support inverse skos relationships

Dockerfile
Parameterised Uvicorn host and port settings in the Dockerfile ENTRYPOINT, providing default values to enhance configurability in deployment scenarios
=> allow port and host to be configurable when running Prez from Docker

dev/dev-setup.py, prez/app.py, prez/models/profiles_item.py, prez/models/search_method.py, prez/reference_data/endpoints/catprez_endpoints.ttl, prez/reference_data/endpoints/profiles_endpoints.ttl, prez/reference_data/endpoints/spaceprez_endpoints.ttl, prez/reference_data/endpoints/vocprez_endpoints.ttl, prez/reference_data/profiles/catprez_default_profiles.ttl, prez/reference_data/profiles/prez_default_profiles.ttl, prez/reference_data/profiles/spaceprez_default_profiles.ttl, prez/reference_data/profiles/vocprez_default_profiles.ttl, prez/routers/catprez.py, prez/routers/management.py, prez/routers/object.py, prez/routers/search.py, prez/routers/vocprez.py, prez/sparql/objects_listings.py, tests/catprez/test_endpoints_catprez.py, tests/data/catprez/expected_responses/catalog_listing_anot.ttl, tests/data/catprez/expected_responses/resource_anot.ttl, tests/data/catprez/expected_responses/resource_listing_anot.ttl, tests/data/catprez/input/_system-catalog.ttl, tests/data/catprez/input/pd_democat.ttl, tests/management/conftest.py, tests/management/test_endpoints_management.py, tests/vocprez/test_endpoints_vocprez.py
Root endpoint ("/") now includes:
- the Prez version (when run directly with Python this will display as "0.1.0.dev0" .
- the annotation predicates Prez will look for (for labels, descriptions, and provenance) to annotate data when the annotated turtle mediatype (text/anot+turtle) is requested. These are provided as an ordered list in terms of the priority a consumer should use them in if more than one predicate is present. This list is configurable via environment variables - see prez/config.
- A list of endpoint information, example shown below:
```
endpoint:catalog-listing a ont:ListingEndpoint ;
ont:deliversClasses prez:CatalogList ;
ont:isTopLevelEndpoint "true"^^xsd:boolean ;
ont:baseClass dcat:Catalog ;
ont:endpointTemplate "/c/catalogs" ;
.
```
At this point the endpoints listed …
=> restructure Catprez Endpoints and add annotation listings to root endpoint

prez/config.py
add '= None' to conform to new pydantic rules.
=> update pydantic syntax for sparql settings

prez/services/model_methods.py
Bugfix to ensure links are created where an object has >1 class. Wrap call to graph.objects() with list() to create an iterable and prevent generator being consumed on first iteration of for loop.
=> Link Genreation bugfix

prez/routers/sparql.py, prez/sparql/methods.py
For some reason, the previous implementation won't work with query parameters passed to the `httpx.URL` object as the result becomes a double URL encoded value. This happens when we send a SPARQL query using Postman but not via the Yasgui client.
Postman:
_Testing with https://meyerweb.com/eric/tools/dencoder/, it requires the value to be decoded twice_.
```
b'query=PREFIX%2520rdf:%2520%253Chttp:%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%2523%253E%250APREFIX%2520skos:%2520%253Chttp:%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%2523%253E%250ASELECT%2520*%2520WHERE%2520%7B?s%2520?p%2520?obj%2520.FILTER%2520(?p%2520IN%2520(skos:prefLabel)%2520)FILTER%2520regex(str(?s),%2520%2522id%2FLexicon%2FNamedRockUnit%2522)FILTER%2520(regex(lcase(str(?obj)),%2520%2522slate%2522))%7D'
```
Using …
=> Fix: Prez SPARQL endpoint's handling of url encoding/decoding of queries in GET requests

prez/app.py, prez/cache.py, prez/dependencies.py, prez/routers/profiles.py, prez/services/model_methods.py, tests/test_endpoints_profiles.py
Fixes profiles by creating a system store with Pyoxigraph for system data. At this point only profiles are added to this system graph. When a profiles related endpoint is called, this internal system repo is used. The RDFLib graph cache is still used elsewhere. Ultimately the Pyoxigraph store for system data can replace the various RDFLib caches.
Fixes #184
=> Fix broken profiles

prez/app.py, prez/config.py, prez/dependencies.py, prez/routers/catprez.py, prez/routers/object.py, prez/routers/profiles.py, prez/routers/search.py, prez/routers/spaceprez.py, prez/routers/vocprez.py, prez/services/link_generation.py, prez/services/listings.py, prez/services/objects.py
Improves the performance of link generation by using pyoxigraph for profiles queries instead of rdflib.
=> Improve performance for link generation

.github/workflows/on_release.yaml
We no longer set the version via an environment variable. It is now bumped on release and read at runtime from `pyproject.toml`.
This brings it in line with how we are managing versioning in prez-ui.
=> Bump poetry version on release

Dockerfile
I was hoping that the prez version is read from `pyproject.toml` but it is not being set when the container image is built via GH Actions for some reason.
This PR sets the `PREZ_VERSION` environment variable in the Dockerfile itself. The prez application will use this as the fallback version if it cannot read from `pyproject.toml`.
=> build: add PREZ_VERSION environment variable to Dockerfile

.dockerignore, .gitignore, Dockerfile, prez/config.py, pyproject.toml
I found some inconsistencies and bugs while building Prez in a docker container for deployment on Azure cloud.
This is a collection of five small commits related to building the Prez bdist wheel, installing it in the Docker container, and building the Docker container.
[1](https://github.com/RDFLib/prez/commit/f4db5690511d046c44dd1ab79df5b06fda6dd5bc) Use arg/env variable for venv creation instead of hardcoded location. (It used the venv in other calls, just not in the venv creation command). Explicitly call the venv version of pip3 to install the wheel, so it is obvious the built prez module is being installed in the venv site_packages.
[2](https://github.com/RDFLib/prez/commit/70fcb45da9eeb9db0d90157d6c910a5a2bb0a7d7) Don't copy the whole source tree into the final image, it already has …
=> Docker build and wheel dist build fixes

prez/renderers/renderer.py
Fixes missing filetype extension for annotated mediatype downloads.
see: http://localhost:8000/v/vocab?_profile=prfl:mem&_mediatype=text/anot+turtle
=> override anotated mediatypes

Dockerfile, main.py, prez/app.py, prez/config.py, tests/test_count.py, tests/test_curie_endpoint.py, tests/test_dd_profiles.py, tests/test_endpoints_cache.py, tests/test_endpoints_catprez.py, tests/test_endpoints_management.py, tests/test_endpoints_object.py, tests/test_endpoints_profiles.py, tests/test_endpoints_spaceprez.py, tests/test_endpoints_vocprez.py, tests/test_redirect_endpoint.py, tests/test_search.py, tests/test_sparql.py
See [this thread](https://github.com/encode/uvicorn/issues/492) for discussion of the benefits of the factory pattern in Uvicorn. Support for this feature was merged to Uvicorn in Oct 2020, and is commonly used. It is also supported in other ASGI runners.
This change set was motivated initially for my need to pass a base prefix (aka, `root_path`) to the `FastAPI()` constructor in `prez.app` (for deploying in a container on Azure). After modifying the app creation code to allow parameterising the construction, it was immediately obvious I could allow other variables to parameterize the creation of the `FastAPI` instance. This led to even being able to optionally use a whole different `Settings` instance if the user wants to manually create their own and pass it in rather than using the one …
=> Change to app factory pattern

prez/services/curie_functions.py
Simplify prefix generation for a URL, and fix the bug in the generation where a URI uses a fragment to split identifiers.
=> Fix bug in generating a prefix for a URI where the URI uses a fragement

prez/app.py, prez/models/model_exceptions.py, prez/routers/sparql.py, prez/services/exception_catchers.py, prez/sparql/methods.py, tests/test_sparql.py
When Prez is behind Azure APIM, all URL query args are limited 2048 characters long.
sparql queries should not really be sent with GET requests anyway.
Add a POST endpoint for the /sparql passthru feature.
This causes the proxied query to the graph db to be called as a POST too
=> Add a POST endpoint for the /sparql passthru feature.

prez/services/app_service.py, tests/data/prefixes/data_using_prefixes.ttl, tests/data/prefixes/remote_prefixes.ttl, tests/test_remote_prefixes.py
Prefixes can be declared in remote repositories using the vann namespace as per the example below. These are loaded first and will take priority over namespaces declared within the `prez/reference_data/prefixes/*.ttl` files.
```
@prefix vann: <http://purl.org/vocab/vann/> .
[ vann:preferredNamespacePrefix "altr-ext" ;
vann:preferredNamespaceUri <http://www.w3.org/ns/dx/connegp/altr-ext#>
] .
```
=> Add ability to declare prefixes in remote Repos

prez/services/link_generation.py, prez/services/listings.py, prez/services/objects.py
1. Remove use of blank nodes when specifying prez members
2. Add prez:FocusNode declaration for object and listing results
Previous output:
```
exm:CatalogOne a dcat:Catalog ;
prez:identifier "exm:CatalogOne" ;
prez:label "Catalog One" ;
prez:link "/catalogs/exm:CatalogOne" ;
prez:members [ 
prez:link "/catalogs/exm:CatalogOne/collections" .
]
```
New output after code changes:
```
exm:CatalogOne a dcat:Catalog ;
prez:identifier "exm:CatalogOne" ;
prez:label "Catalog One" ;
prez:link "/catalogs/exm:CatalogOne" ;
prez:members "/catalogs/exm:CatalogOne/collections" ;
prez:type prez:FocusNode .
```
=> Simplify prez:members declaration; add prez:FocusNode class to focus nodes

prez/services/link_generation.py
1. Add triples for the identifier and label of link parent components. 
2. Bugfix to prevent creation of links for top concepts/narrowers endpoints (which were generating incorrectly - and are not necessarily required.)
Example of triples now being added for parent components in a link:
```
exm:TopLevelConcept a skos:Concept ;
dcterms:identifier "exm:TopLevelConcept"^^prez:identifier ;
prez:label "The toppiest of concepts" ;
prez:link "/catalogs/exm:VocPrezCatalog/collections/exm:SchemingConceptScheme/items/exm:TopLevelConcept" .
exm:VocPrezCatalog dcterms:identifier "exm:VocPrezCatalog"^^prez:identifier ;
prez:label "A Demo Catalog" .
```
=> Triples for parent link components + Bugfix to remove links for top concepts / narrowers endpoints

prez/renderers/renderer.py, tests/test_pmt_headers.py
As per issue https://github.com/idn-au/catalogue-data/issues/35 The
returned RDF files did not have appropriate filenames.
This PR adds a filename where possible to the returned RDF via the `Content-Disposition` header.
=> compute better filenames for returned rdf

prez/reference_data/profiles/ogc_records_profile.ttl
Modify default profile to exclude skos:hasTopConcept to prevent timeouts when loading ConceptSchemes. The top concepts can be obtained using the paginated endpoint `/concept-hierarchy/<cs>/top-concepts`. Remove optional inclusion of concept skos:inScheme conceptScheme links for the same reason.
=> Remove properties from ConceptScheme rendering for performance reasons

prez/config.py, prez/dependencies.py, prez/services/listings.py, prez/services/query_generation/search.py, tests/test_query_construction.py
Search result counts are now consistent with listing counts:
If limit of 20 is requested:
- a search with limit N+1 = 21 is performed
- if the results count = 21, then ">20" is returned,
- otherwise the result count is returned as a string (e.g. 14 results returns "14")
Separately, the default search limit has been set to 10, and is configurable via "search_count_limit" on the app settings.
=> fix: Search counts behave the same as listing counts

prez/app.py, prez/config.py, prez/routers/sparql.py, tests/conftest.py, tests/test_sparql.py
Makes the SPARQL endpoint opt in using the enable_sparql_endpoint variable in settings; defaulted to False.
=> SPARQL endpoint opt in

prez/repositories/remote_sparql.py
Raise a ValueError on startup when a RemoteSparqlRepo is configured, but SPARQL_ENDPOINT is not provided in the settings file or the env var.
Fixes #260
=> Raise a early error when a RemoteSparqlRepo is configured, but SPARQL_ENDPOINT is none.

prez/reference_data/profiles/vocprez_default_profiles.ttl, prez/sparql/objects_listings.py
Fix vocpub profile to display all properties for concepts by adding a "shext:allPredicateValues" special predicate.
V4 will implement similar functionality.
=> Fix vocpub profile to display all properties for concepts

prez/config.py
small fix to allow setting of labelling predicates via environment variable.
=> merge lawson/label_predicates into maintenance-v3

Dockerfile
best practice and prevents an error in alpine3.20 which was inhibiting
the pipx installation of poetry
=> fix: pin alpine version

prez/dependencies.py, prez/reference_data/endpoints/data_endpoints_default/default_endpoints.ttl, test_data/catprez.ttl, tests/test_endpoints_catprez.py, tests/test_node_selection_shacl.py
Updates Catalog hierarchy to dcat:Catalog / dcat:Resource. Retains dcat:Catalog / dcat:Dataset which is the "parent" of geo:FeatureCollections in "spaceprez".
Bugfix for remote profiles not being loaded to the system (pyoxigraph) store.
=> Remote profiles bugfix and update to Catalog hierarchy

prez/config.py, prez/services/link_generation.py, prez/services/objects.py
Redirect object requests to their HTML views when either `text/html` or no media type is requested.
=> HTML redirect to Prez UI

prez/services/connegp_service.py
You will now only get the alternates profile if you specifically request it. Otherwise if any other profile is available, you'll get that. This will prevent unintended behaviour in the UI where the Alternates Profile was equally "ranked" with another profile, so either could be returned on page refresh.
=> Deprioritise Alternates Profile

prez/reference_data/profiles/ogc_features.ttl, prez/reference_data/profiles/ogc_records_profile.ttl, prez/reference_data/profiles/prez_default_profiles.ttl, prez/services/annotations.py, prez/services/generate_profiles.py, prez/services/query_generation/count.py
1. Ensure only prez related profiles are loaded from remote stores by updating the profile selection query
2. Type profiles used to declare default profiles as prez:IndexProfiles. This makes 1 easier
3. Fix count query bug. Counts could previously be wrong in some instances - moved DISTINCT to correct place.
4. Improve performance of annotations retrieval. Identified slow code and changed to a faster implementation.
=> Only retrieve remote Prez profiles; count query bug; annotation performance

prez/dependencies.py, prez/exceptions/model_exceptions.py, prez/reference_data/endpoints/features/features_nodeshapes.ttl, prez/reference_data/profiles/ogc_features.ttl, prez/reference_data/profiles/ogc_records_profile.ttl, prez/reference_data/profiles/prez_default_profiles.ttl, prez/routers/ogc_features_router.py, prez/services/annotations.py, prez/services/curie_functions.py, prez/services/generate_profiles.py, prez/services/listings.py, prez/services/objects.py, prez/services/query_generation/count.py
1. OGC Features bugfix for auto generated queryables.
2. Add upfront validation of curie -> URI and raise URI not found exception if appropriate. 
3. Add special characters to those excluded from CURIE generation: "aeiou!@#$%^&*()_+-=,."
=> OGC Features queryables bugfix + cleaner curie generation

README.md, prez/repositories/remote_sparql.py
Allows properly forwarding POST SPARQL queries to data repo.
=> Implement SPARQL POST in remote_sparql repo

prez/config.py
extended to include alt and hidden labels as per the recommendation in
#282
=> extend default search predicates

.github/workflows/release.yaml
I think it wasnt being run because of incorrect extension
=> fix: rename release workflow

README-Dev.md, poetry.lock, prez/reference_data/cql/default_context.json, prez/services/listings.py, prez/services/query_generation/cql.py, pyproject.toml, test_data/cql/expected_generated_queries/additional_temporal_disjoint_instant.rq, test_data/cql/expected_generated_queries/additional_temporal_during_intervals.rq, test_data/cql/expected_generated_queries/clause7_12.rq, test_data/cql/expected_generated_queries/clause7_13.rq, test_data/cql/expected_generated_queries/example20.rq, test_data/cql/expected_generated_queries/example21.rq, test_data/cql/expected_generated_queries/example22.rq, test_data/cql/expected_generated_queries/example27.rq, test_data/cql/expected_generated_queries/example53.rq, test_data/cql/expected_generated_queries/example54.rq, test_data/cql/expected_generated_queries/example55.rq, test_data/cql/expected_generated_queries/example56.rq, test_data/cql/expected_generated_queries/example57.rq, test_data/cql/expected_generated_queries/example58.rq, test_data/cql/expected_generated_queries/example59.rq, test_data/cql/expected_generated_queries/example60.rq, test_data/cql/expected_generated_queries/example61.rq, test_data/cql/expected_generated_queries/example62.rq, test_data/cql/expected_generated_queries/example63.rq, test_data/cql/expected_generated_queries/example64.rq, test_data/cql/expected_generated_queries/example65.rq, test_data/cql/expected_generated_queries/example66.rq, test_data/cql/expected_generated_queries/example67.rq, tests/test_ogc.py
- adds caching of Feature Collection query (the details of a feature collection are required to be included in the GeoJSON response for *each* page of a /items response, so the same Feature Collection query is called repeatedly. A 10 minute cache has been added with aiocache.
- While caching may still be used in future, the query performance will be improved by converting the blank node selection blocks to equivalent UNION clauses.
- add JSON LD context back to the CQL queries. This is to work with the existing implementation of CQL -> SPARQL. As the test cases from OGC contained no URIs, a JSON LD context was applied to them to create URIs for testing against RDF. While this was helpful to have a reference set of test cases, it has caused other issues in parsing and would in hindsight be …
=> Feature Collection caching + bugfix for CQL context

.github/workflows/release.yaml, .releaserc.yaml, pyproject.toml
Python semantic release was only used to auto update the version
variable in pyproject.toml, but this does not work with branch
protection rules and so is not neccessary anymore. Thus it is better to
use the more common semantic-release action which works with branch
protection rules as it does not need to commit any files as part of the
release.
=> ci: migrate from python-semantic-release to semantic-release

README-Dev.md
docs: Update docs with basic info on semantic release process. Confirm that PR title needs updating when doing a squash in order to trigger release.
NB three commits have been used in order to confirm when squashing commits that the PR title must be updated.
=> docs: David/update docs sem rel

prez/reference_data/profiles/ogc_features.ttl, prez/reference_data/profiles/ogc_records_profile.ttl, prez/reference_data/profiles/prez_default_profiles.ttl, prez/renderers/renderer.py, prez/services/listings.py, prez/services/query_generation/shacl.py, tests/test_property_selection_shacl.py
a few performance and functionality updates:
- Within the OGC Features API, for features listing, remove use of second query that retrieved CBD of the parent Feature Collection. This includes removal of the manually included inbound triple patterns. Both inbound patterns and the properties of the parent feature collection can be specified in profiles using sh:inversePath, including via [ sh:inversePath shext:allPredicateValues ] to get all inbound triples to a focus node ( ?inbound_s ?inbound_p ?focus_node ). Sequence paths can be used for specific properties of the parent Feature Collection.
- Modify blank node constructs to be a series of UNION clauses of the form:
```sparql
{
?focus_node ?bn_p_1 ?bn_o_1 .
?bn_o_1 ?bn_p_1 ?bn_o_2
FILTER isBLANK(?bn_o_1)
}
UNION
{
?focus_node ?bn_p_1 …
```
=> feat: wildcard inbound properties and performance improvement for blank node selection

prez/cache.py, prez/services/generate_profiles.py
Where remote profiles are defined with two classes (e.g. a ListingProfile that is also an ObjectProfile), the existing profile retrieval DESCRIBE incorrectly retrieved triples for the profile twice. a SELECT DISTINCT has been included in the WHERE clause to prevent this.
Self approving as this is a one line change.
=> fix: retrieve remote profiles only once

prez/renderers/renderer.py, prez/services/connegp_service.py, prez/services/listings.py
reduce header length in OGC Features API listings (at /features/collections/). Issue should not appear at .../items as the links here are not per item. Reduce number of mediatypes shown at /features/collections/ in order to reduce link header size. NB other RDF mediatypes, including annotated ones, can still be requested/returned using the Accept header or _mediatype query parameter as before.
=> fix: reduce OGC Features link header length for collections

prez/reference_data/profiles/ogc_features.ttl, prez/reference_data/profiles/ogc_records_profile.ttl, prez/reference_data/profiles/prez_default_profiles.ttl, prez/services/link_generation.py, prez/services/query_generation/shacl.py, tests/test_property_selection_shacl.py
Shacl path should have a bnode as it's range not an RDF Collection. This is a basic error/typo that has been present for some time and somehow not caused issues until now (potentially due to default RDF ordering in RDFLib). Using an RDF Collection meant that one of either the union of property paths OR the shacl:union property itself were processed, potentially RDFLib typically ordered these internally in such a way that the list and not sh:union was processed. Olis seems to have disrupted this. In any case, use of an RDF Collection is wrong.
The following two changes have been made:
1. Fix the processing of sh:union statements, these were the only thing specified off of RDF Collections from sh:path
2. Fix the relevant profiles to use blank nodes instead of RDF Collections ( "(" -> "[" )
=> fix: range of sh:path should be blank node not RDF Collection

prez/services/query_generation/classes.py
improve performance of classes SPARQL query by changing the values clause to an equivalent inline data clause. This also accommodates a bug in qlever.
=> perf: improve classes query

docs/development.md, prez/models/query_params.py, prez/reference_data/endpoints/base/endpoint_nodeshapes.ttl, prez/reference_data/profiles/ogc_features.ttl, prez/reference_data/profiles/ogc_records_profile.ttl, prez/reference_data/profiles/prez_default_profiles.ttl, prez/services/connegp_service.py, prez/services/query_generation/umbrella.py
Summary: This PR ensures that when a search or CQL query is run _directly from the /search or /CQL endpoints **only_**, there is no focus node class restriction triple added i.e. the `?focus_node rdf:type <class>`. It also ensures that search/cql queries are directed to appropriate profiles _in the default profiles_.
Previously the default profiles used did not add this triple. This change ensures there is no restriction on the profiles.
Implementation: add a check to the umbrella query builder that if a search or CQL query is received ONLY on the /search or /cql endpoints, then the class information for the types of objects is excluded from the generated SPARQL query. search and CQL queries received on other listing endpoints will still apply the class filter relevant to that endpoint.\ …
=> fix: exclude class triple for plain search and cql searches

prez/repositories/remote_sparql.py
instead get the content-type from the response and fall back to
n-triples if not given
=> fix: don't assume RDF from remote endpoint is n-triples

.github/workflows/release.yaml
tested build on seperate action and it was successful. looks like the
issue with pyoxigraph and arm is resolved.
=> ci: add arm64 container build

README.md
Just updating the link from the old RDFTools validator to https://tools.dev.kurrawong.ai/validate
=> chore: Update RDFtools link

prez/services/link_generation.py
do not attempt to create links where there's no path node, the query will fail. This occurs when e.g.: request to /catalogs, prez finds that the class is geo:Feature, endpoint nodeshapes at levels 1&3, for third level, query fails as there's no path nodes available (between first and third levels, as the request was to /catalogs). Probably easier not to duplicate classes at different hierarchy levels where possible.
=> fix: do not attempt to create links where there's no path node

prez/dependencies.py
url_path.replace("features/collections", "features") to url_path.replace("/features/collections", "/features") to prevent incorrectly replacing on curies that happen to end with 'features'
lets come back to this later and add some tests
=> fix: hierarchy level calculation for ogc features api

prez/dependencies.py, prez/routers/base_router.py
adds correct api documentation for the `/object` endpoint.
NB docs point users to use `iri` however `uri` is still supported so this is not a breaking change.
=> fix: add missing api docs for /object endpoint. change from uri to iri

prez/services/objects.py
Redirection to prez-ui should work even without a prez:link to the `/object?uri=...` prez-ui endpoint.
Additionally, return a 404 when the item graph is empty (ie no data found about the resource). This may not be 100% correct, though, because the item may exist but not have any data for a given profile...
=> fix: redirects to existing resources without a prez:link

poetry.lock, prez/services/query_generation/cql.py, prez/services/query_generation/shacl.py, prez/services/query_generation/umbrella.py, pyproject.toml, tests/test_cql.py, tests/test_cql_queryable.py, tests/test_property_selection_shacl.py, tests/test_shacl_sequence_alternative_paths.py
**PR Summary:**
This PR improves SHACL and CQL query generation, focusing on better handling of complex paths and logical conditions.
**Highlights:**
* **SHACL Path Handling (a40541f, 69cee6c):**
* Added handling of alternate paths within sequence paths, specifically for the endpoints use case in subselects. 
* Also extended processing of alternate paths to within sequence paths in general i.e. within profiles:
* Refactored `SequencePath` to correctly process `AlternativePath` using `UNION` blocks in `WHERE` and separate triples in `CONSTRUCT`.
* Improved support for nested and recursive SHACL property paths.
* **CQL Logical Conditions (3431edb, af0e670):**
* Enhanced recursive parsing of nested `AND`/`OR` conditions.
* Fixed incorrect triple placement from `OR` branches using a depth …
=> fix: cql nested and/or handling and alt paths within seq paths

prez/services/query_generation/shacl.py, tests/test_filter_shape.py
Implements support for SHACL sh:filterShape to enable conditional triple pattern emission based on sibling property constraints. This allows profiles to emit triples only when the subject node satisfies specific filter conditions using standard SHACL vocabulary.
The implementation adds _parse_filter_shape() method to extract filter conditions and enhances path processing to handle filter shapes. Filter conditions are automatically flattened and applied directly to the focus node, with context guards preventing infinite recursion during processing.
Example Usage:
```turtle
sh:property [
sh:path ( sosa:hasResult rdf:value ) ;
sh:filterShape [
sh:property [
sh:path ( [ sh:inversePath rdf:value ] [ sh:inversePath sosa:hasResult ] ) ;
sh:property [
sh:path sosa:observedProperty ;
sh:hasValue …
```
=> feat: add shacl filterShape support for conditional triple pattern emission

poetry.lock, pyproject.toml, test_data/cql/expected_generated_queries/additional_temporal_disjoint_instant.rq, test_data/cql/expected_generated_queries/additional_temporal_during_intervals.rq, test_data/cql/expected_generated_queries/clause7_12.rq, test_data/cql/expected_generated_queries/clause7_13.rq, test_data/cql/expected_generated_queries/example20.rq, test_data/cql/expected_generated_queries/example21.rq, test_data/cql/expected_generated_queries/example22.rq, test_data/cql/expected_generated_queries/example27.rq, test_data/cql/expected_generated_queries/example53.rq, test_data/cql/expected_generated_queries/example54.rq, test_data/cql/expected_generated_queries/example55.rq, test_data/cql/expected_generated_queries/example56.rq, test_data/cql/expected_generated_queries/example57.rq, test_data/cql/expected_generated_queries/example58.rq, test_data/cql/expected_generated_queries/example59.rq, test_data/cql/expected_generated_queries/example60.rq, test_data/cql/expected_generated_queries/example61.rq, test_data/cql/expected_generated_queries/example62.rq, test_data/cql/expected_generated_queries/example63.rq, test_data/cql/expected_generated_queries/example64.rq, test_data/cql/expected_generated_queries/example65.rq, test_data/cql/expected_generated_queries/example66.rq, test_data/cql/expected_generated_queries/example67.rq, tests/test_cql.py, tests/test_property_selection_shacl.py, tests/test_shacl_sequence_alternative_paths.py
Update sparql grammar pydantic. TriplesBlock will now always produce a full stop "." per triple (including cases where it isn't required). This is to cover cases where multiple TriplesBlocks with a single triple are used together and previously did not terminate their single triples with a "."
=> fix: update sparql grammar to terminate all triples same subject path with fullstop

prez/services/query_generation/search_default.py, prez/services/query_generation/umbrella.py
The query generates `?focus_node` variable twice in the sub select distinct query.
Before the fix:
```sparql
CONSTRUCT {
?focus_node <https://prez.dev/type> <https://prez.dev/FocusNode> .
?focus_node <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?prof_1_node_1 .
?hashID <https://prez.dev/searchResultWeight> ?weight .
?hashID <https://prez.dev/searchResultPredicate> ?pred .
?hashID <https://prez.dev/searchResultMatch> ?match .
?hashID <https://prez.dev/searchResultURI> ?focus_node .
?hashID <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://prez.dev/SearchResult>
}
WHERE {
{
SELECT DISTINCT ?focus_node ?focus_node ?pred ?match ?weight (URI(CONCAT("urn:hash:", SHA256(CONCAT(STR(?focus_node), STR(?pred), STR(?match), STR(?weight))))) AS ?hashID)
WHERE {
{
SELECT ?focus_node ?pred …
```
=> fix: search query default, subquery defines ?focus_node variable twice

prez/app.py, prez/config.py, prez/dependencies.py, prez/services/prez_logging.py, tests/conftest.py, tests/test_pyoxigraph_in_memory_store_storage.py, tests/test_pyoxigraph_store_disk_storage.py
This PR adds support for using an on-disk store with the pyoxigraph data store backend.
If the environment variable `PYOXIGRAPH_DATA_DIR` is set, the data store will treat the specified location as a valid oxigraph data directory and operate in persistent (on-disk) mode instead of the default in-memory mode.
Not sure why log propagation was originally disabled. Without log propagation, I couldn't use caplog to capture the logs in tests.
Let me know if this needs to be added back in. We can make it configurable via settings so that we can enable it in tests and disable it in deployments.
=> feat: add on-disk data store for pyoxigraph

.gitignore, prez/cache.py, prez/dependencies.py
Each request was creating a new pyoxigraph `Store` and trying to access the same directory. This PR ensures only one store is created and reused across requests.
=> fix: pyoxigraph persistent store lock contention

prez/services/query_generation/cql.py, tests/test_cql.py, tests/test_query_construction.py
Fixes #402 
This adds `?focus_node` as a static always-present Variable for the inner SUBSELECT on the CQL query generation.
This is required because #387 removed the addtion of "?focus_node" from the umbrella query.
As @recalcitrantsupplant mentioned in #387, its better to have the Search and CQL query generation include `?focus_node" themselves rather than add it in the umbrella, so the subquery is complete in and of itself, for testing purposes.
Evidently there was no testing for this, because the CQL query breakage flew under the radar.
=> fix: for missing ?focus_node var on inner subselect for CQL-genreated SUBSELECT query

prez/services/connegp_service.py
When a specific profile isn't requested, and prez cannot find a profile to use for the object class, it falls back to hardcoded profiles  - open-object for Object endpoint, mem (Members) for Listing endpoint.
The problem is this fallback profile uses a single hardcorded mediatype "text/anot+turtle". Even if you have header "Accept: text/turtle" in the request or "?_mediatype=text/turtle" in the QSA, prez will still always use "text/anot+turtle".
https://github.com/RDFLib/prez/blob/cc8c3cac4ab3bc0580e65539f4568c43be28512e/prez/services/connegp_service.py#L217-L224
https://github.com/RDFLib/prez/blob/cc8c3cac4ab3bc0580e65539f4568c43be28512e/prez/services/connegp_service.py#L226-L233
In this PR:
Instead of using hardcoded mediatypes in fallback profiles, try to use the one that is requested …
=> fix: try to use request accept mediatype in fallback profile

prez/services/listings.py, tests/test_ogc_features_manual.py
Looks like a copy+paste error made its way into the Oxigraph changes.
When using the OGC-Featues API listing endpoint, if requesting an annotation mediatype like `anot+turtle` then Prez crashes because it tries to serialize the oxigraph ItemStore twice.
=> fix: remove extra serialize line that breaks oxigraph serialize

prez/app.py, prez/config.py, prez/repositories/remote_sparql.py, prez/services/exception_catchers.py, tests/test_remote_sparql_timeout.py
1. The existing timeout parameter which applied for requests to Prez is now also passed on to remote triplestore backends as a query parameter, with the name of the query parameter specified via the `sparql_timeout_param_name` config setting (settle by an upper case environment variable of the same name). It has been defaulted to the name "timeout" as this is used by both Fuseki and GraphDB which are the triplestores predominantly used with Prez.
This is to prevent long running execution of SPARQL queries in the triplestore after Prez has already timed out on a given query.
2. The default timeout for Prez has been updated to 60 seconds, it remains configurable using "sparql_timeout". The same timeout value is passed to the triplestore.
3. Timeout exceptions are now raised as …
=> feat: pass on timeout to remote triplestores and ensure httpx errors are returned

docs/fuseki_fts_functionality.md, prez/services/query_generation/search_fuseki_fts.py, prez/services/query_generation/shacl.py
When using the FTS profile functionality (which caters to focus nodes not directly linked to search result matches).
Presumably this worked when the functionality was first introduced and has since regressed.
I thought the functionality was documented but I cannot find it so I've added a doc.
Edit: I've decided to roll in the fix for https://github.com/RDFLib/prez/issues/412 here too.
This is a design decision - if end users want specific lucene behaviour they can pass in valid lucene syntax; prez will only escape as necessary and otherwise not touch the query.
=> fix: generates separate unique identifiers for intermediate nodes in fuseki fts profiles

prez/services/query_generation/grammar_helpers.py, tests/test_cql.py
Translate CQL boolean literals into true/false filters in SPARQL by teaching convert_value_to_rdf_term to return BooleanLiteral instances for Python bools, which keeps the generated FILTER clauses semantically correct. Added a regression test that
exercises a simple boolean equality and confirms the emitted query now reads FILTER (?var_1 = true). Test run: pytest tests/test_cql.py::test_cql_boolean_equals_filter.
=> fix: cql boolean handling should come out in sparql as true false not 1 or 0

docs/faceted_search.md, prez/dependencies.py, prez/services/listings.py, prez/services/query_generation/facet.py, tests/test_search_empty_term.py
This branch allows search queries without a search term (q parameter) when filtering/faceting parameters are provided.
Key Changes:
- Enhanced search flexibility: Modified prez/dependencies.py:270-305 to allow empty/missing search terms when filtering parameters (facet_profile, filter, bbox, datetime) are present
- Improved error messaging: Updated error message to guide users toward available filtering options
- Comprehensive test coverage: Added tests/test_search_empty_term.py with 8 test cases covering both legacy behavior (requiring search term) and new behavior (allowing empty term with filters)
Before: Search endpoint required a search term (q) parameter, returning 400 error if missing
After: Search endpoint accepts empty/missing search term when any filtering parameter is provided, …
=> feat: allow no query string search
